# Form implementation generated from reading ui file 'ui\designer\font_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FontDialog(object):
    def setupUi(self, FontDialog):
        FontDialog.setObjectName("FontDialog")
        FontDialog.resize(450, 500)
        FontDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(FontDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fontFamilyGroup = QtWidgets.QGroupBox(parent=FontDialog)
        self.fontFamilyGroup.setObjectName("fontFamilyGroup")
        self.fontFamilyLayout = QtWidgets.QVBoxLayout(self.fontFamilyGroup)
        self.fontFamilyLayout.setObjectName("fontFamilyLayout")
        self.fontFamilyListView = QtWidgets.QListView(parent=self.fontFamilyGroup)
        self.fontFamilyListView.setShowGrid(False)
        self.fontFamilyListView.setAlternatingRowColors(True)
        self.fontFamilyListView.setObjectName("fontFamilyListView")
        self.fontFamilyLayout.addWidget(self.fontFamilyListView)
        self.verticalLayout.addWidget(self.fontFamilyGroup)
        self.fontOptionsLayout = QtWidgets.QHBoxLayout()
        self.fontOptionsLayout.setObjectName("fontOptionsLayout")
        self.fontStyleGroup = QtWidgets.QGroupBox(parent=FontDialog)
        self.fontStyleGroup.setObjectName("fontStyleGroup")
        self.fontStyleLayout = QtWidgets.QVBoxLayout(self.fontStyleGroup)
        self.fontStyleLayout.setObjectName("fontStyleLayout")
        self.fontStyleListView = QtWidgets.QListView(parent=self.fontStyleGroup)
        self.fontStyleListView.setShowGrid(False)
        self.fontStyleListView.setAlternatingRowColors(True)
        self.fontStyleListView.setObjectName("fontStyleListView")
        self.fontStyleLayout.addWidget(self.fontStyleListView)
        self.fontOptionsLayout.addWidget(self.fontStyleGroup)
        self.fontSizeGroup = QtWidgets.QGroupBox(parent=FontDialog)
        self.fontSizeGroup.setObjectName("fontSizeGroup")
        self.fontSizeLayout = QtWidgets.QVBoxLayout(self.fontSizeGroup)
        self.fontSizeLayout.setObjectName("fontSizeLayout")
        self.fontSizeListView = QtWidgets.QListView(parent=self.fontSizeGroup)
        self.fontSizeListView.setShowGrid(False)
        self.fontSizeListView.setAlternatingRowColors(True)
        self.fontSizeListView.setObjectName("fontSizeListView")
        self.fontSizeLayout.addWidget(self.fontSizeListView)
        self.fontOptionsLayout.addWidget(self.fontSizeGroup)
        self.verticalLayout.addLayout(self.fontOptionsLayout)
        self.fontEffectsGroup = QtWidgets.QGroupBox(parent=FontDialog)
        self.fontEffectsGroup.setObjectName("fontEffectsGroup")
        self.effectsLayout = QtWidgets.QGridLayout(self.fontEffectsGroup)
        self.effectsLayout.setObjectName("effectsLayout")
        self.strikeoutCheckBox = QtWidgets.QCheckBox(parent=self.fontEffectsGroup)
        self.strikeoutCheckBox.setObjectName("strikeoutCheckBox")
        self.effectsLayout.addWidget(self.strikeoutCheckBox, 0, 0, 1, 1)
        self.underlineCheckBox = QtWidgets.QCheckBox(parent=self.fontEffectsGroup)
        self.underlineCheckBox.setObjectName("underlineCheckBox")
        self.effectsLayout.addWidget(self.underlineCheckBox, 0, 1, 1, 1)
        self.colorLabel = QtWidgets.QLabel(parent=self.fontEffectsGroup)
        self.colorLabel.setObjectName("colorLabel")
        self.effectsLayout.addWidget(self.colorLabel, 1, 0, 1, 1)
        self.colorLayout = QtWidgets.QHBoxLayout()
        self.colorLayout.setObjectName("colorLayout")
        self.colorPreview = QtWidgets.QFrame(parent=self.fontEffectsGroup)
        self.colorPreview.setMinimumSize(QtCore.QSize(30, 30))
        self.colorPreview.setMaximumSize(QtCore.QSize(30, 30))
        self.colorPreview.setAutoFillBackground(False)
        self.colorPreview.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.colorPreview.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.colorPreview.setObjectName("colorPreview")
        self.colorLayout.addWidget(self.colorPreview)
        self.colorButton = QtWidgets.QPushButton(parent=self.fontEffectsGroup)
        self.colorButton.setObjectName("colorButton")
        self.colorLayout.addWidget(self.colorButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.colorLayout.addItem(spacerItem)
        self.effectsLayout.addLayout(self.colorLayout, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.fontEffectsGroup)
        self.previewGroup = QtWidgets.QGroupBox(parent=FontDialog)
        self.previewGroup.setObjectName("previewGroup")
        self.previewLayout = QtWidgets.QVBoxLayout(self.previewGroup)
        self.previewLayout.setObjectName("previewLayout")
        self.previewTextEdit = QtWidgets.QTextEdit(parent=self.previewGroup)
        self.previewTextEdit.setReadOnly(True)
        self.previewTextEdit.setObjectName("previewTextEdit")
        self.previewLayout.addWidget(self.previewTextEdit)
        self.verticalLayout.addWidget(self.previewGroup)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=FontDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Apply|QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(FontDialog)
        self.buttonBox.accepted.connect(FontDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(FontDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FontDialog)

    def retranslateUi(self, FontDialog):
        _translate = QtCore.QCoreApplication.translate
        FontDialog.setWindowTitle(_translate("FontDialog", "Font Settings"))
        self.fontFamilyGroup.setTitle(_translate("FontDialog", "Font Family"))
        self.fontStyleGroup.setTitle(_translate("FontDialog", "Font Style"))
        self.fontSizeGroup.setTitle(_translate("FontDialog", "Size"))
        self.fontEffectsGroup.setTitle(_translate("FontDialog", "Effects"))
        self.strikeoutCheckBox.setText(_translate("FontDialog", "Strikeout"))
        self.underlineCheckBox.setText(_translate("FontDialog", "Underline"))
        self.colorLabel.setText(_translate("FontDialog", "Color:"))
        self.colorButton.setText(_translate("FontDialog", "Change Color..."))
        self.previewGroup.setTitle(_translate("FontDialog", "Preview"))
        self.previewTextEdit.setHtml(_translate("FontDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz 1234567890</p></body></html>"))
