# Form implementation generated from reading ui file 'ui\designer\help_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HelpDialog(object):
    def setupUi(self, HelpDialog):
        HelpDialog.setObjectName("HelpDialog")
        HelpDialog.resize(800, 600)
        HelpDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(HelpDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(parent=HelpDialog)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(parent=self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_search = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_search.setClearButtonEnabled(True)
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.verticalLayout_2.addWidget(self.lineEdit_search)
        self.treeView_contents = QtWidgets.QTreeView(parent=self.layoutWidget)
        self.treeView_contents.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.treeView_contents.setHeaderHidden(True)
        self.treeView_contents.setObjectName("treeView_contents")
        self.verticalLayout_2.addWidget(self.treeView_contents)
        self.textBrowser_helpContent = QtWidgets.QTextBrowser(parent=self.splitter)
        self.textBrowser_helpContent.setOpenExternalLinks(True)
        self.textBrowser_helpContent.setObjectName("textBrowser_helpContent")
        self.verticalLayout.addWidget(self.splitter)
        self.frame = QtWidgets.QFrame(parent=HelpDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_back = QtWidgets.QPushButton(parent=self.frame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/back.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_back.setIcon(icon)
        self.pushButton_back.setObjectName("pushButton_back")
        self.horizontalLayout.addWidget(self.pushButton_back)
        self.pushButton_forward = QtWidgets.QPushButton(parent=self.frame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/forward.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_forward.setIcon(icon1)
        self.pushButton_forward.setObjectName("pushButton_forward")
        self.horizontalLayout.addWidget(self.pushButton_forward)
        self.pushButton_home = QtWidgets.QPushButton(parent=self.frame)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_home.setIcon(icon2)
        self.pushButton_home.setObjectName("pushButton_home")
        self.horizontalLayout.addWidget(self.pushButton_home)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.frame)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(HelpDialog)
        self.buttonBox.accepted.connect(HelpDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(HelpDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(HelpDialog)

    def retranslateUi(self, HelpDialog):
        _translate = QtCore.QCoreApplication.translate
        HelpDialog.setWindowTitle(_translate("HelpDialog", "Help"))
        self.lineEdit_search.setPlaceholderText(_translate("HelpDialog", "Search help..."))
        self.pushButton_back.setText(_translate("HelpDialog", "Back"))
        self.pushButton_forward.setText(_translate("HelpDialog", "Forward"))
        self.pushButton_home.setText(_translate("HelpDialog", "Home"))
