# Form implementation generated from reading ui file 'ui\designer\message_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MessageDialog(object):
    def setupUi(self, MessageDialog):
        MessageDialog.setObjectName("MessageDialog")
        MessageDialog.resize(400, 250)
        MessageDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(MessageDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_header = QtWidgets.QFrame(parent=MessageDialog)
        self.frame_header.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_header.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_header.setObjectName("frame_header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_icon = QtWidgets.QLabel(parent=self.frame_header)
        self.label_icon.setMinimumSize(QtCore.QSize(32, 32))
        self.label_icon.setMaximumSize(QtCore.QSize(32, 32))
        self.label_icon.setText("")
        self.label_icon.setObjectName("label_icon")
        self.horizontalLayout_2.addWidget(self.label_icon)
        self.label_title = QtWidgets.QLabel(parent=self.frame_header)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_2.addWidget(self.label_title)
        self.verticalLayout.addWidget(self.frame_header)
        self.textBrowser_message = QtWidgets.QTextBrowser(parent=MessageDialog)
        self.textBrowser_message.setOpenExternalLinks(True)
        self.textBrowser_message.setObjectName("textBrowser_message")
        self.verticalLayout.addWidget(self.textBrowser_message)
        self.checkBox_dontShowAgain = QtWidgets.QCheckBox(parent=MessageDialog)
        self.checkBox_dontShowAgain.setObjectName("checkBox_dontShowAgain")
        self.verticalLayout.addWidget(self.checkBox_dontShowAgain)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=MessageDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(MessageDialog)
        self.buttonBox.accepted.connect(MessageDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(MessageDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MessageDialog)

    def retranslateUi(self, MessageDialog):
        _translate = QtCore.QCoreApplication.translate
        MessageDialog.setWindowTitle(_translate("MessageDialog", "Message"))
        self.label_title.setText(_translate("MessageDialog", "Dialog Title"))
        self.checkBox_dontShowAgain.setText(_translate("MessageDialog", "Don\'t show this message again"))
