# Form implementation generated from reading ui file 'ui\designer\prompt_list_item.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PromptListItem(object):
    def setupUi(self, PromptListItem):
        PromptListItem.setObjectName("PromptListItem")
        PromptListItem.resize(400, 50)
        PromptListItem.setMinimumSize(QtCore.QSize(0, 50))
        self.horizontalLayout = QtWidgets.QHBoxLayout(PromptListItem)
        self.horizontalLayout.setContentsMargins(8, 4, 8, 4)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.promptNameLabel = QtWidgets.QLabel(parent=PromptListItem)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.promptNameLabel.sizePolicy().hasHeightForWidth())
        self.promptNameLabel.setSizePolicy(sizePolicy)
        self.promptNameLabel.setObjectName("promptNameLabel")
        self.horizontalLayout.addWidget(self.promptNameLabel)
        self.tagLabel = QtWidgets.QLabel(parent=PromptListItem)
        self.tagLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.tagLabel.setStyleSheet("QLabel {\n"
"  color: #333333;\n"
"  background-color: transparent;\n"
"  border: 1px solid #CCCCCC;\n"
"  border-radius: 3px;\n"
"  padding: 2px 6px;\n"
"}")
        self.tagLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tagLabel.setObjectName("tagLabel")
        self.horizontalLayout.addWidget(self.tagLabel)
        self.infoButton = QtWidgets.QToolButton(parent=PromptListItem)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\designer\\../resources/images/info.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.infoButton.setIcon(icon)
        self.infoButton.setObjectName("infoButton")
        self.horizontalLayout.addWidget(self.infoButton)

        self.retranslateUi(PromptListItem)
        QtCore.QMetaObject.connectSlotsByName(PromptListItem)

    def retranslateUi(self, PromptListItem):
        _translate = QtCore.QCoreApplication.translate
        PromptListItem.setWindowTitle(_translate("PromptListItem", "Prompt List Item"))
        self.promptNameLabel.setText(_translate("PromptListItem", "Prompt Name"))
        self.tagLabel.setText(_translate("PromptListItem", "Category"))
        self.infoButton.setText(_translate("PromptListItem", "i"))
